# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 081e64c59745e3f111d785a617ddcb85389a9622aa3a8edc96b61fc247926501efaf59f314a138b27e38333134aae97eac50bd2a375572e8904a37f68f3583af

test:
  secret_key_base: d9e3da312c65653a451b59d7e5ac6157618ddcc3f0186ca7069c7e89eea7d0f435aab87ed5eb11a5db70ba7d07d6fd1f299606c844804023a86f648992888529

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
